---
name: Ultrasonics
version: dev1
slug: mopidy_percy
panel_icon: mdi:music-circle
description: Playlist management
url: https://github.com/Gurutasker/addon-mopidy-lounge-prod
arch:
  - amd64
auth_api: true
audio: true
ports:
  5000/tcp: 5001
ports_description:
  5000/tcp: Web interface (Not required for Ingress)
map:
  - config
  - share:rw
  - ssl
  - media:rw
options:
  system_packages: []
  python_packages: []
  settings: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  settings:
    - name: str
      value: str
  leave_front_door_open: bool?
